// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: content.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContent = `-- name: CreateContent :one
INSERT INTO contents (schema_id, data, created_by)
VALUES ($1, $2, $3)
RETURNING id, schema_id, data, created_by, created_at, updated_at, deleted_at
`

type CreateContentParams struct {
	SchemaID  pgtype.Int4
	Data      []byte
	CreatedBy pgtype.Int4
}

func (q *Queries) CreateContent(ctx context.Context, arg CreateContentParams) (Content, error) {
	row := q.db.QueryRow(ctx, createContent, arg.SchemaID, arg.Data, arg.CreatedBy)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.SchemaID,
		&i.Data,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteContent = `-- name: DeleteContent :exec
UPDATE contents
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) DeleteContent(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteContent, id)
	return err
}

const getContentsBySchema = `-- name: GetContentsBySchema :many
SELECT id, schema_id, data, created_by, created_at, updated_at, deleted_at FROM contents
WHERE schema_id = $1
AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetContentsBySchema(ctx context.Context, schemaID pgtype.Int4) ([]Content, error) {
	rows, err := q.db.Query(ctx, getContentsBySchema, schemaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Content
	for rows.Next() {
		var i Content
		if err := rows.Scan(
			&i.ID,
			&i.SchemaID,
			&i.Data,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
