// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Content struct {
	ID        int32
	SchemaID  pgtype.Int4
	Data      []byte
	CreatedBy pgtype.Int4
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type Schema struct {
	ID         int32
	Name       string
	Definition []byte
	CreatedBy  pgtype.Int4
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	DeletedAt  pgtype.Timestamp
}

type User struct {
	ID           int32
	Email        string
	PasswordHash string
	Role         string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	DeletedAt    pgtype.Timestamp
}
