// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
)

type Content struct {
	ID        int32
	SchemaID  sql.NullInt32
	Data      json.RawMessage
	CreatedBy sql.NullInt32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type Schema struct {
	ID         int32
	Name       string
	Definition json.RawMessage
	CreatedBy  sql.NullInt32
	CreatedAt  sql.NullTime
	DeletedAt  sql.NullTime
}

type User struct {
	ID           int32
	Username     string
	PasswordHash string
	Role         string
	CreatedAt    sql.NullTime
	DeletedAt    sql.NullTime
}
