// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schemas.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSchema = `-- name: CreateSchema :one
INSERT INTO schemas (name, definition, created_by)
VALUES ($1, $2, $3)
RETURNING id, name, definition, created_by, created_at, updated_at, deleted_at
`

type CreateSchemaParams struct {
	Name       string
	Definition []byte
	CreatedBy  pgtype.Int4
}

func (q *Queries) CreateSchema(ctx context.Context, arg CreateSchemaParams) (Schema, error) {
	row := q.db.QueryRow(ctx, createSchema, arg.Name, arg.Definition, arg.CreatedBy)
	var i Schema
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Definition,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteSchema = `-- name: DeleteSchema :exec
UPDATE schemas
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) DeleteSchema(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSchema, id)
	return err
}

const getSchemaByID = `-- name: GetSchemaByID :one
SELECT id, name, definition, created_by, created_at, updated_at, deleted_at FROM schemas
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSchemaByID(ctx context.Context, id int32) (Schema, error) {
	row := q.db.QueryRow(ctx, getSchemaByID, id)
	var i Schema
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Definition,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSchemaByName = `-- name: GetSchemaByName :one
SELECT id, name, definition, created_by, created_at, updated_at, deleted_at FROM schemas
WHERE name = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSchemaByName(ctx context.Context, name string) (Schema, error) {
	row := q.db.QueryRow(ctx, getSchemaByName, name)
	var i Schema
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Definition,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listSchemas = `-- name: ListSchemas :many
SELECT id, name, definition, created_by, created_at, updated_at, deleted_at FROM schemas
WHERE deleted_at IS NULL
ORDER BY id
`

func (q *Queries) ListSchemas(ctx context.Context) ([]Schema, error) {
	rows, err := q.db.Query(ctx, listSchemas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schema
	for rows.Next() {
		var i Schema
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Definition,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
